### PR TITLE
Added db schema

### PR DESCRIPTION
**Pull request by DavidSciola**
db schema was based off the following:
Hibernate: create table multiplechoice_question_options (multiplechoice_question_id bigint not null, options varchar(255))
Hibernate: create table multiplechoice_question_responses (multiplechoice_question_id bigint not null, responses integer)
Hibernate: create table open_answer_question_responses (open_answer_question_id bigint not null, responses varchar(255))
Hibernate: create table question (dtype varchar(31) not null, id bigint not null, prompt varchar(255), high float(24), low float(24), survey_id bigint, primary key (id))
Hibernate: create table range_question_responses (range_question_id bigint not null, responses float(24))
Hibernate: create table survey (id bigint not null, name varchar(255), open boolean not null, primary key (id))
Hibernate: create table survey_questions (survey_id bigint not null, questions_id bigint not null)

### CODE REVIEW

**Comment by DavidSciola** [comment]
> responses

**Comment by DavidSciola** [comment]
I made it so that only the primary keys are highlighted. The question response ids are not highlighted since they are referencing the ids in the question table.

**Comment by kevinhquach** [comment]
Alright, lgtm

**Review by DavidHaighton — APPROVED** [review]
```
 _                        _
| |__   __ _ ___  ___  __| |
| '_ \ / _` / __|/ _ \/ _` |
| |_) | (_| \__ |  __| (_| |
|_.__/ \__,_|___/\___|\__,_|
```

**Pull request merged**
